name: E2E
on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      NEXT_TELEMETRY_DISABLED: 1
      CI: 1
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r apps/adk-orchestrator/requirements.txt PyJWT
          cd apps/terminal-daemon && npm ci
          cd ../console && npm ci --include=dev
      - name: Install Playwright
        run: |
          cd apps/console && npx playwright install --with-deps
      - name: Generate dev JWT
        run: |
          python - <<'PY' > dev.env
          import datetime, jwt
          token = jwt.encode({'sub': 'dev', 'exp': datetime.datetime.utcnow() + datetime.timedelta(minutes=5)}, 'dev-secret', algorithm='HS256')
          print(f'DEV_JWT={token}')
          print(f'NEXT_PUBLIC_DEV_BEARER={token}')
          PY
          cat dev.env >> "$GITHUB_ENV"
      - name: Start services
        run: |
          export PYTHONPATH="${GITHUB_WORKSPACE}:${PYTHONPATH}"
          (cd apps/adk-orchestrator && PYTHONPATH="${PYTHONPATH}" uvicorn main:app --host 127.0.0.1 --port 8080) > uvicorn.log 2>&1 &
          echo $! > uvicorn.pid
          (cd apps/terminal-daemon && node server.js) &
          echo $! > daemon.pid
          (cd apps/console && PORT=3001 npm run dev) &
          echo $! > console.pid
          
          # Wait for orchestrator
          for i in {1..30}; do
            if curl -fsS http://127.0.0.1:8080/healthz >/dev/null 2>&1; then
              echo "Orchestrator health check passed"
              break
            fi
            echo "Waiting for orchestrator... ($i/30)"
            sleep 1
          done
          if ! curl -fsS http://127.0.0.1:8080/healthz >/dev/null 2>&1; then
            echo "Orchestrator health check failed after 30 seconds"
            echo "=== Uvicorn logs ==="
            cat uvicorn.log || echo "No uvicorn.log found"
            exit 1
          fi
          
          # Wait for console
          for i in {1..60}; do
            if curl -fsS http://127.0.0.1:3001 >/dev/null 2>&1; then
              echo "Console health check passed"
              break
            fi
            echo "Waiting for console... ($i/60)"
            sleep 1
          done
          if ! curl -fsS http://127.0.0.1:3001 >/dev/null 2>&1; then
            echo "Console health check failed after 60 seconds"
            exit 1
          fi
      - name: Smoke test – click "Run Plan"
        run: |
          cat > apps/console/e2e.spec.ts <<'TS'
          import { test, expect } from '@playwright/test';
          test('run plan returns JSON', async ({ page }) => {
            await page.goto('http://localhost:3001/');
            await page.getByRole('button', { name: 'Run Plan' }).click();
            await expect(page.locator('pre')).toContainText('run_id');
          });
          TS
          cd apps/console && npx playwright test e2e.spec.ts --reporter=list
      - name: Stop
        if: always()
        run: |
          kill $(cat console.pid) || true
          kill $(cat daemon.pid) || true
          kill $(cat uvicorn.pid) || true