name: CI
on: [push, pull_request]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Install terminal daemon deps
        run: cd apps/terminal-daemon && npm ci || true
      - name: Install orchestrator deps
        run: |
          python -m pip install --upgrade pip
          pip install -r apps/adk-orchestrator/requirements.txt
      - name: Lint/Type/Test (placeholder)
        run: echo "TODO: add lint/type/tests"
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Secret scan (placeholder)
        run: echo "TODO: detect-secrets scan"