name: Contract
on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  contract:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -r apps/adk-orchestrator/requirements.txt
          pip install schemathesis PyJWT
      - name: Start orchestrator
        run: |
          cd apps/adk-orchestrator && uvicorn main:app --host 127.0.0.1 --port 8080 &
          echo $! > uvicorn.pid
          echo "Waiting for orchestrator to start..."
          for i in {1..60}; do
            if curl -fsS http://127.0.0.1:8080/healthz >/dev/null 2>&1; then
              echo "Orchestrator started successfully after ${i} seconds"
              break
            fi
            echo "Attempt ${i}/60: Orchestrator not ready yet..."
            sleep 1
          done
          # Final check with error reporting
          if ! curl -fsS http://127.0.0.1:8080/healthz >/dev/null 2>&1; then
            echo "❌ Orchestrator failed to start after 60 seconds"
            echo "Process status:"
            ps aux | grep uvicorn || echo "No uvicorn processes found"
            exit 1
          fi
      - name: Generate dev JWT
        run: |
          python - <<'PY' >> $GITHUB_ENV
import datetime, jwt
token = jwt.encode({'sub': 'dev', 'exp': datetime.datetime.utcnow() + datetime.timedelta(minutes=5)}, 'dev-secret', algorithm='HS256')
print(f'DEV_JWT={token}')
PY
      - name: Schemathesis against /v1
        run: |
          schemathesis run api-specs/orchestrator-v1.yaml --base-url http://127.0.0.1:8080 \
            --checks all --hypothesis-max-examples=50 \
            -H "Authorization: Bearer $DEV_JWT" \
            --endpoint "/v1/runs/plan" --stateful=links
      - name: Stop
        if: always()
        run: kill $(cat uvicorn.pid) || true
